import type { Metadata } from "next";
import "./styles/globals.css";
import ReactQueryProvider from "./providers/QueryProvider";
import { Header } from "@/widgets/header/Header";
import { getUserServer } from "@/shared/libs/auth/getCurrentUser"
import { dehydrate, QueryClient } from "@tanstack/react-query";
import { queryKeys } from "@/shared/keys/query-keys";
import ThemeRegistry from "./providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export  default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   
  async function getUser(){
     const queryClient = new QueryClient()

    try{
      await queryClient.prefetchQuery({
        queryKey:queryKeys.user.me(),
        queryFn: getUserServer
      })
      
      const dehydratedState = dehydrate(queryClient)
      return dehydratedState

      
    } catch (error) {

    return undefined;
  }
}
 
  const dehydratedState = await getUser();
 
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider dehydratedState={dehydratedState}>
          <ThemeRegistry>
          <Header />
          {children}
          </ThemeRegistry>
          </ReactQueryProvider>
      </body>
    </html>
  );
}
