import type { Metadata } from "next";
import "./styles/globals.css";
import ReactQueryProvider from "./providers/QueryProvider";
import { Header } from "@/widgets/header/Header";
import { getUserServer } from "@/shared/libs/auth/getCurrentUser";
import { dehydrate, QueryClient } from "@tanstack/react-query";
import { queryKeys } from "@/shared/keys/query-keys";
import { AppThemeProvider } from "./providers/ThemeProvider";
import { RestaurantProvider } from "./providers/RestaurantContext";
import { Sidebar } from "@/widgets/(admin)/dashboard/Sidebar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  async function getUser() {
    const queryClient = new QueryClient();

    try {
      await queryClient.prefetchQuery({
        queryKey: queryKeys.user.me(),
        queryFn: getUserServer,
      });

      const dehydratedState = dehydrate(queryClient);
      return dehydratedState;
    } catch (error) {
      return undefined;
    }
  }

  const dehydratedState = await getUser();

  return (
    <html lang="en">
      {/* We use h-screen to prevent scrolling in the main body, and flex to distribute elements */}
      <body className=" h-screen bg-gray-100">
        <ReactQueryProvider dehydratedState={dehydratedState}>
          <AppThemeProvider>
            <Toaster richColors position="top-center" />
            {children}
          </AppThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
